service: quarkus-aws-lambda

frameworkVersion: '3'

plugins:
  - serverless-plugin-scripts

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: java11
  timeout: 30

package:
  artifact: target/function.zip

custom:
  scripts:
    hooks:
      'deploy:finalize': date >> date.log


functions:
  hello:
    handler: not.used.in.provided.runtime
    runtime: provided
    memorySize: 256
    environment:
      DISABLE_SIGNAL_HANDLERS: true
      AUTHOR: zhang