service: quarkus-aws-lambda

frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: java11
  timeout: 30

package:
  artifact: target/function.zip

functions:
  hello:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    memorySize: 256